name: Deploy to Linode

on:
  push:
    branches: [ main ]
    paths:
      - "backend/**"
      - "Dockerfile"
      - "docker-compose.yml"
      - "Caddyfile"
      - ".github/workflows/deploy.yml"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Sanity check inputs (debug)
        run: |
          echo "USER=${{ vars.SERVER_USER }}"
          echo "HOST=${{ vars.SERVER_HOST }}"
          test -n "${{ vars.SERVER_USER }}" && test -n "${{ vars.SERVER_HOST }}" || { echo "Missing vars"; exit 1; }

      - name: Deploy over SSH
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ vars.SERVER_HOST }}
          username: ${{ vars.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script_stop: true
          script: |
            set -euo pipefail
            cd ~
            ls -l deploy.sh
            bash -lc './deploy.sh'
